version: "3"

services:
        api:
                build: ./api
                ports:
                        - "3001:3001"
                volumes:
                        - ./api:/usr/src/app
                links:
                        - db
                command: sh -c "cargo watch -x run -w src -w Cargo.toml"
                env_file:
                         - ./.env

        db:
                image: "postgres:latest"
                ports:
                        - "5433:5433"
                volumes:
                        - ./.database:/var/lib/postgresql/data/pgdata
                env_file:
                        - ./.env
