version: "3"

services:
        api:
                build: ./api
                ports:
                        - "3001:3001"
                volumes:
                        - ./api:/usr/src/app
                links:
                        - db
                command: sh -c "cargo watch -x run -w src -w Cargo.toml"
                env_file:
                         - ./.env

        db:
                restart: "always"
                image: "postgres:14.1-alpine"
                ports:
                        - "5433:5432"
                volumes:
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
                        - ./.database:/var/lib/postgresql/data/pgdata
                env_file:
                        - ./.env

volumes:
        .database: