[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2.1"
dotenv = "0.15.0"

db = { package = "db", path = "./src/db" }